### ISSUE TITLE
please fix your bug on class EthCrossChainManager#91

### ISSUE THREAD

**Issue by jambestwick** [polynetwork/eth-contracts#13]
[code anlysis](https://pbs.twimg.com/media/E8eIlWsWUAE4GBT?format=jpg&name=large)
![E8eIlWsWUAE4GBT](https://user-images.githubusercontent.com/18340126/128962873-c7c875a7-271b-4224-ba65-1f97ef381151.jpg)

**Comment by tanZiWen** [comment]
thank you so much.
